# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Soma Details"
subtitle: "Elevation with new media design"
author:  "Riley Soma Fires"
header:
 title: "Soma Details"
 subtitle: "Riley Soma Fires"
footer:
 name: "Who am I"
 bio: "New medias creative and editor. Founder, game director, and lead programmer for Swarm & Swarm 2 by Riley Soma and Eddy Katt.  VR/XR, Digital 3D, 360 Panorama, Boutique Neural Net Shaders. Ask me about my math."
social_urls:
  instagram: "https://www.instagram.com/rileysoma"
  twitter: "https://twitter.com/"